language: ruby
rvm: 2.1
env:
  global:
    - GIT_COMMITTER_NAME='Takeshi Yabe'
    - GIT_COMMITTER_EMAIL='tyabe@nilidea.com'
    - GIT_AUTHOR_NAME='Takeshi Yabe'
    - GIT_AUTHOR_EMAIL='tyabe@nilidea.com'
    - secure: KBNwhHqRKGxAvKpywA0vyyAGsJ+i65CPk/cutVjDPLEFqG3cfZUBdWgsiKtTcP4OhP5FgvmRECqPbiAI0sOJKSbVORe5wwPgUtmaBq19sEla7AuO3tVzrWik7nNaSqyDCQLW5ZOdx2+nBOzk3TEyHsiHj9ZUYbKKOjZR5L4NdOk=
branches:
  only: source
  except: master

before_script: '[ "$TRAVIS_BRANCH" == "source" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success: '[ "$TRAVIS_BRANCH" == "source" ] && [ "$GH_TOKEN" ] && rake deploy'

